# Generated by Django 3.2 on 2021-05-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fetch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('imdb', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(default='00:00:00', max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='static/media/')),
                ('nota', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100, null=True, unique=True)),
                ('image', models.ImageField(default='DefaultImageDino.png', upload_to='static/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('season', models.IntegerField(default=1)),
                ('chapter', models.IntegerField(default=1)),
                ('image', models.ImageField(default='default.png', upload_to='static/media/')),
                ('nota', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
