# Generated by Django 3.1.7 on 2021-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media_pictures')),
                ('season', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
            ],
        ),
    ]
