# Generated by Django 3.2 on 2021-05-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='user',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.CharField(max_length=90, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='user',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
