# Generated by Django 3.1.7 on 2021-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20210513_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(default='static/media/default.png', upload_to='static/media/'),
        ),
    ]
