# Generated by Django 3.1.7 on 2021-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20210513_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(default='default.png', upload_to='static/media'),
        ),
    ]
