# Generated by Django 3.1.7 on 2021-05-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0009_auto_20210514_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='series',
            name='platform',
        ),
        migrations.AlterField(
            model_name='series',
            name='chapter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='season',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='static/media')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
