# Generated by Django 3.1.7 on 2021-05-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20210522_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notes',
        ),
    ]
