# Generated by Django 3.1.7 on 2021-05-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fetch',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=500)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.films')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.series')),
            ],
        ),
    ]
