# Generated by Django 3.1.7 on 2021-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_fetch_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetch',
            name='imdb',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='fetch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='films',
            name='time',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='season',
            field=models.IntegerField(default=1),
        ),
    ]
