# Generated by Django 3.1.7 on 2021-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20210524_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetch',
            name='imdb',
        ),
        migrations.AlterField(
            model_name='fetch',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
