# Generated by Django 3.1.7 on 2021-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20210524_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetch',
            name='imdb',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fetch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
